[package]
name = "pub-ip"
version = "1.5.0"
authors = ["Ryan"]
edition = '2021'
description = "A quick rust script to print or write your public IPv4 address"
readme = "README.md"
repository = "https://github.com/FIRED3STROYER/pub-ip"
license = "GPLv3"
license-file = "LICENSE.txt"

[dependencies]
curl = "0.4.43"
clap = { version = "3.2.8", features = ["derive"] }